version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: pip
    directory: /exporter
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: npm
    directory: /front
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /exporter
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /front
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
