apiVersion: v1
kind: Service
metadata:
  name: {{ include "exporter.fullname" . }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.reloadPort }}
      targetPort: reload
      protocol: TCP
      name: reload
  selector:
    {{- include "exporter.selectorLabels" . | nindent 4 }}
