apiVersion: v1
kind: Service
metadata:
  name: edge-metrics-exporter-generic
  namespace: monitoring
  labels:
    app: edge-metrics-exporter-generic
spec:
  clusterIP: None
  selector:
    app: edge-metrics-exporter-generic
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
    - name: management
      port: 9101
      targetPort: 9101
